# Generated by Django 5.2.5 on 2025-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('qte_total', models.IntegerField(default=0)),
                ('qte_avant_3m', models.IntegerField(default=0)),
                ('qte_apres_3m_avant_6m', models.IntegerField(default=0)),
                ('qte_apres_6m_avant_12m', models.IntegerField(default=0)),
                ('qte_apres_12m_avant_18m', models.IntegerField(default=0)),
                ('qte_apres_18m_avant_24m', models.IntegerField(default=0)),
                ('qte_apres_24m_avant_36m', models.IntegerField(default=0)),
                ('qte_apres_36m', models.IntegerField(default=0)),
            ],
        ),
    ]
