# Generated by Django 5.2.5 on 2025-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('qte', models.IntegerField(blank=True, null=True)),
                ('val_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicament',
            name='val_achat_apres_12m_avant_18m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='val_achat_apres_18m_avant_24m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='val_achat_apres_24m_avant_36m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='val_achat_apres_36m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='val_achat_apres_3m_avant_6m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='val_achat_apres_6m_avant_12m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='val_achat_avant_3m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='val_total_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='med_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_apres_12m_avant_18m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_apres_18m_avant_24m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_apres_24m_avant_36m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_apres_36m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_apres_3m_avant_6m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_apres_6m_avant_12m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_avant_3m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
