# Generated by Django 5.2.5 on 2025-09-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0002_medicament2_medicament_val_achat_apres_12m_avant_18m_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicament2',
        ),
        migrations.CreateModel(
            name='Medicament2',
            fields=[
            ],
            options={
                'verbose_name': 'Medicament2',
                'verbose_name_plural': 'Medicament2',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medicament.medicament',),
        ),
    ]
