# Generated by Django 5.2.5 on 2025-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0002_stock_stpmedicament_delete_medicament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('med_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='STPMedicament',
        ),
    ]
