# Generated by Django 5.2.5 on 2025-09-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0003_delete_medicament2_medicament2'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='valeur_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
