# Generated by Django 5.2.5 on 2025-09-03 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0003_medicament_delete_stock_delete_stpmedicament'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_lt_3m', models.IntegerField(default=0)),
                ('qty_3_6m', models.IntegerField(default=0)),
                ('qty_gt_6m', models.IntegerField(default=0)),
                ('med', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicament.medicament')),
            ],
        ),
    ]
